### ISSUE TITLE
Addition of login and singup page 

### ISSUE THREAD

**Issue by Aaryanb45** [Akshat111111/new-and-easy-Travel#18]
making it more appealing and attractive

**Comment by Akshat111111** [comment]
any progress??

**Comment by Aaryanb45** [comment]
yh threw I will show u full flexed page

**Comment by Aaryanb45** [comment]
<img width="1465" alt="Screenshot 2024-07-15 at 7 34 37 PM" src="https://github.com/user-attachments/assets/9fc826fe-e0df-4566-9847-00b80cb75686">

**Comment by Aaryanb45** [comment]
how's ittt

**Comment by Aaryanb45** [comment]
in this the images are keep on changing
every 3 sec

**Comment by Aaryanb45** [comment]
https://github.com/user-attachments/assets/49956e97-11ff-4763-ba52-1f78ff72452f

**Comment by Akshat111111** [comment]
no worries, it works

**Comment by Aaryanb45** [comment]
how much points will u assign
as u didn't assign any points to me

**Comment by Akshat111111** [comment]
let me talk to organizers
