### ISSUE TITLE
Readme Update required 

### ISSUE THREAD

**Issue by Meetjain1** [Akshat111111/new-and-easy-Travel#25]
Want to update readme file by adding some animated emojis , ss of the website , contributors section and some minor changes. 

@Akshat111111 assign this to me I will create it , I am working under VSOC . Thanks

**Comment by deepesh611** [comment]
@Meetjain1 make sure to add how to setup the project on their system.

`npm install`, `npm run dev`/`yarn run dev`, etc.

**Comment by Meetjain1** [comment]
> @Meetjain1 make sure to add how to setup the project on their system.
> 
> `npm install`, `npm run dev`/`yarn run dev`, etc.

Can I also reduce the text ? @deepesh611

**Comment by deepesh611** [comment]
> > @Meetjain1 make sure to add how to setup the project on their system.
> > `npm install`, `npm run dev`/`yarn run dev`, etc.
> 
> Can I also reduce the text ? @deepesh611

imo, you can. In the end, a README is suppose to be only the summary off the project. It contains the following:

- Summary of your project
- If we want to contribute, how to set the project on our local machines

`OPTIONAL THINGS`
- U can add contributor's profiles to readme
- tech/tools used, etc.



`JUST TO BE CLEAR` : imo -> in my opinion

**Comment by Meetjain1** [comment]
> > > @Meetjain1 make sure to add how to setup the project on their system.
> > > `npm install`, `npm run dev`/`yarn run dev`, etc.
> > 
> > 
> > Can I also reduce the text ? @deepesh611
> 
> imo, you can. In the end, a README is suppose to be only the summary off the project. It contains the following:
> 
> * Summary of your project
> * If we want to contribute, how to set the project on our local machines
> 
> `OPTIONAL THINGS`
> 
> * U can add contributor's profiles to readme
> * tech/tools used, etc.
> 
> `JUST TO BE CLEAR` : imo -> in my opinion

@deepesh611 sure

**Comment by Meetjain1** [comment]
@deepesh611 file is ready have a look . Thanks

**Comment by deepesh611** [comment]
> @deepesh611 file is ready have a look . Thanks

Well, I cannot see the upated file unless the PR is merged, and its not my opinion that matters, the opinion should be of the repo owner, if he/she is satisfied with your changes
