### ISSUE TITLE
Add more responsiveness

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/new-and-easy-Travel#3]
There are some buttons which are not responsive, so make it responsive

**Comment by kratik1237** [comment]
please assign me I am interested this issue @Akshat111111

**Comment by kratik1237** [comment]
@Akshat111111 i did the issue #3 , add more responsive website

**Comment by kratik1237** [comment]
Can you give points? @Akshat111111

**Comment by Akshat111111** [comment]
will update soon

**Comment by kratik1237** [comment]
@Akshat111111 okay, how many

**Comment by kratik1237** [comment]
Points are not updated?? @Akshat111111

**Comment by Akshat111111** [comment]
will do it soon, this week i am very busy with my exams

**Comment by kratik1237** [comment]
Okay @Akshat111111

**Comment by kratik1237** [comment]
@Akshat111111  points are not update???

**Comment by kratik1237** [comment]
@Akshat111111 can you assign the points?

**Comment by Akshat111111** [comment]
I have already shared the spreadsheet with the program admin

**Comment by kratik1237** [comment]
@Akshat111111 thank you
