### ISSUE TITLE
Remove the error of login page 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/new-and-easy-Travel#6]
Currently the login page is not working, so correct it

**Comment by TomLucasakaTGeek** [comment]
@Akshat111111  assign this issue to me

**Comment by Akshat111111** [comment]
any progress??

**Comment by TomLucasakaTGeek** [comment]
Sir I havent looked into it as of yet

**Comment by Akshat111111** [comment]
no worries, move at your own pace
